batikalongan/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('catalog/', include('catalog.urls')),
    path('article/', include('article.urls')),
    path('', include('authentication.urls')),
    # path('accounts/', include('allauth.urls')),
    path('timeline/', include('timeline.urls')),
    path('event/', include('event.urls')),
    path('', include('main.urls')),
re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
path('auth/', include('authentication.urls')),
] 

# # Ini digunakan untuk development mode
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# batikalongan/main/urls.py
from django.urls import path
from .views import main_landing_page

app_name = 'main'

urlpatterns = [
    path('', main_landing_page, name='main_landing_page'),
]

timeline/urls.py
from django.urls import path
from timeline.views import *
from django.conf.urls.static import static
# from .import views

app_name = 'timeline'

urlpatterns = [
    path('', home_view, name='home'),
    path('post/create/', post_create_view, name='post-create'),
    path('post/delete/<pk>/', post_delete_view, name='post-delete'),
    path('post/edit/<pk>/', post_edit_view, name='post-edit'),
    path('post/<pk>/', post_page_view, name='post'),
    path('post/like/<pk>/', like_post, name='like-post'),
    path('commentsent/<pk>/', comment_sent, name='comment-sent'),
    path('comment/delete/<pk>/', comment_delete_view, name='comment-delete'),
    path('comment/like/<pk>/', like_comment, name='like-comment'),
    path('reply-sent/<pk>/', reply_sent, name='reply-sent'),
    path('reply/delete/<pk>/', reply_delete_view, name='reply-delete'),
    path('reply/like/<pk>/', like_reply, name='like-reply'),
    path('json/', home_view_json, name='home_json'),
    path('toggle-like/', toggle_like, name='toggle_like'),
    path('delete-post/', delete_post, name='delete_post'),
    path('delete-comment/', delete_comment, name='delete_comment'),
    path('create-post/', create_post, name="create_post"),
    path('create-comment/', create_comment, name='create_comment'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeline/models.py
import uuid
from django.db import models
from django.conf import settings  # Import settings for AUTH_USER_MODEL

class Post(models.Model):
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    title = models.CharField(max_length=500)
    artist = models.CharField(max_length=500, null=True)
    url = models.URLField(max_length=500, null=True)
    image = models.URLField(max_length=500)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='posts')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="likedposts", through="LikedPost")
    files = models.FileField(null=True, blank=True, upload_to='file_uploads/')

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-created']


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='comments')
    parent_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.CharField(max_length=150)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likedcomments', through='LikedComment')
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'

    class Meta:
        ordering = ['-created']


class Reply(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="replies")
    parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="replies")
    body = models.CharField(max_length=150)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likedreplies', through='LikedReply')
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'

    class Meta:
        ordering = ['created']


class LikedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} : {self.post.title}'


class LikedComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} : {self.comment.body[:30]}'


class LikedReply(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} : {self.reply.body[:30]}'

timeline/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class PostCreateForm(ModelForm):
   class Meta:
      model = Post
      fields = ['files', 'body']
      labels = {
         'body' : 'Caption',
      }
      widgets = {
         'body' : forms.Textarea(attrs={'rows': 3, 'class': 'font5 text-4xl'}),
         # 'url' : forms.TextInput(attrs={'placeholder': 'Add urls ...'}),
      }

class PostEditForm(ModelForm):
   class Meta:
      model = Post
      fields = ['body',]
      labels = {
         'body' : '',
      }
      widgets = {
         'body' : forms.Textarea(attrs={'rows': 3, 'class': 'font5 text-4xl'}),
      }

class CommentCreateForm(ModelForm):
   class Meta:
      model = Comment
      fields = ['body',]
      labels = {
         'body' : '',
      }
      widgets = {
         'body' : forms.TextInput(attrs={
            'placeholder': 'Add Comment ...',
            'style': 'resize:none;',
            'class': 'font-semibold text-lg w-full p-4 border rounded-lg shadow-md',
         })
      }

class ReplyCreateForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['body']
        widgets = {
            'body' : forms.TextInput(attrs={'placeholder': 'Add reply ...', 'class': "!text-sm"})
        }
        labels = {
            'body': ''
        }

timeline/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from .models import *
from.forms import *
from django.contrib import messages
from bs4 import BeautifulSoup
import requests
from django.http import JsonResponse
from django.core.serializers import serialize
import json
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .models import Post, LikedPost
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.html import strip_tags

def home_view(request):
   posts = Post.objects.all()
   return render(request, 'posts/home.html', {'posts' : posts})

def post_create_view(request):
    form = PostCreateForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('timeline:home') 
    
    return render(request, 'posts/post_create.html', {'form': form})

def post_delete_view(request, pk):
   post = get_object_or_404(Post, id=pk)
   if request.method == 'POST':
      post.delete()
      messages.success(request, 'Post deleted')
      return redirect('timeline:home')
      
   return render(request, 'posts/post_delete.html', {'post' : post })

def post_edit_view(request, pk):
   post = Post.objects.get(id=pk)
   form = PostEditForm(instance=post)

   if request.method == 'POST':
      form = PostEditForm(request.POST, instance=post)
      if form.is_valid:
         form.save()
         messages.success(request, 'Post updated' )
         return redirect('timeline:home')
   
   context = {
      'post' : post,
      'form' : form,
   }
   return render(request, 'posts/post_edit.html', context)

def post_page_view(request, pk):
   post = get_object_or_404(Post, id=pk)
   commentform = CommentCreateForm()
   replyform = ReplyCreateForm()

   context = {
      'post' : post,
      'commentform' : commentform,
      'replyform' : replyform,
   }

   return render(request, 'posts/post_page.html', context)


def comment_sent(request, pk):
   # post = Post.objects.get(id=pk)
   post = get_object_or_404(Post, id=pk)
   #  replyform = ReplyCreateForm()
    
   if request.method == 'POST':
      form = CommentCreateForm(request.POST)
      if form.is_valid():
         comment = form.save(commit=False)
         comment.author = request.user
         comment.parent_post = post            
         comment.save()
         return redirect('timeline:post', post.id)
      else:
         print(form.errors)

   return redirect('post', post.id)
   #  context = {
   #      'post' : post,
   #      'comment': comment,
   #      'replyform': replyform
   #  }

   #  return render(request, 'snippets/add_comment.html', context)

def comment_delete_view(request, pk):
   post = get_object_or_404(Comment, id=pk, author=request.user)

   if request.method == 'POST':
      post.delete()
      messages.success(request, 'Comment deleted')
      return redirect('timeline:post', post.parent_post.id)
      
   return render(request, 'posts/comment_delete.html', {'comment' : post })


def reply_sent(request, pk):
   comment = get_object_or_404(Comment, id=pk)
    
   if request.method == 'POST':
      form = ReplyCreateForm(request.POST)
      if form.is_valid():
         reply = form.save(commit=False)
         reply.author = request.user
         reply.parent_comment = comment           
         reply.save()

   return redirect('timeline:post', comment.parent_post.id)

def reply_delete_view(request, pk):
   reply = get_object_or_404(Reply, id=pk, author=request.user)

   if request.method == 'POST':
      reply.delete()
      messages.success(request, 'Reply deleted')
      return redirect('timeline:post', reply.parent_comment.parent_post.id)
      
   return render(request, 'posts/reply_delete.html', {'reply' : reply })

def like_post(request, pk):
   post = get_object_or_404(Post, id=pk)
   user_exist = post.likes.filter(username=request.user.username).exists()

   if post.author != request.user:
      if user_exist:
         post.likes.remove(request.user)
      else:
         post.likes.add(request.user)
   
   return render(request,'snip/likes.html',{'post': post})

def like_comment(request, pk):
   comment = get_object_or_404(Comment, id=pk)
   user_exist = comment.likes.filter(username=request.user.username).exists()

   if comment.author != request.user:
      if user_exist:
         comment.likes.remove(request.user)
      else:
         comment.likes.add(request.user)
   
   return render(request,'snip/likes_comment.html',{'comment': comment})

def like_reply(request, pk):
   reply = get_object_or_404(Reply, id=pk)
   user_exist = reply.likes.filter(username=request.user.username).exists()

   if reply.author != request.user:
      if user_exist:
         reply.likes.remove(request.user)
      else:
         reply.likes.add(request.user)
   
   return render(request,'snip/likes_reply.html',{'reply': reply})


   #  def inner_func(func):
   #      def wrapper(request, *args, **kwargs):
            
                    
   #          return func(request, post)
   #      return wrapper
   #  return inner_func

def home_view_json(request):
    user = request.user if request.user.is_authenticated else None
    posts = Post.objects.prefetch_related('likes', 'comments__replies')  # Prefetch related data for efficiency

    posts_json = [
        {
            "id": post.id,
            "author": post.author.username if post.author else None,
            "body": post.body,
            "created": post.created.isoformat(),
            "is_liked_by_user": post.likes.filter(id=user.id).exists() if user else False,
            "like_count": post.likes.count(),
            "comment_count": post.comments.count(),
            "comments": [
                {
                    "id": comment.id,
                    "author": comment.author.username if comment.author else None,
                    "body": comment.body,
                    "created": comment.created.isoformat(),
                }
                for comment in post.comments.all()
            ],
        }
        for post in posts
    ]

    return JsonResponse(posts_json, safe=False)

@csrf_exempt
def toggle_like(request):
    # Parse the incoming JSON request body
    try:
        data = json.loads(request.body)
        post_id = data.get('post_id')
        
        # Ensure post_id is provided
        if not post_id:
            return JsonResponse({'message': 'Post ID is required'}, status=400)

        # Get the post object
        post = Post.objects.get(id=post_id)

        # Check if the user has already liked this post
        existing_like = LikedPost.objects.filter(post=post, user=request.user).first()

        if existing_like:
            # If the user has already liked the post, remove the like
            existing_like.delete()
            message = "Like removed"
        else:
            # If the user hasn't liked the post, add a like
            LikedPost.objects.create(post=post, user=request.user)
            message = "Post liked"

        # Return a JSON response with the message
        return JsonResponse({'message': message})

    except json.JSONDecodeError:
        return JsonResponse({'message': 'Invalid JSON'}, status=400)
    except Post.DoesNotExist:
        return JsonResponse({'message': 'Post not found'}, status=404)

@csrf_exempt  # To disable CSRF validation (use only if necessary)
def delete_post(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            post_id = data.get('post_id')
            
            post = Post.objects.get(id=post_id)
            post.delete()
            
            return JsonResponse({'message': 'Post deleted'}, status=200)
        except Post.DoesNotExist:
            return JsonResponse({'message': 'Post not found'}, status=404)
        except Exception as e:
            return JsonResponse({'message': str(e)}, status=500)
        
@csrf_exempt 
def delete_comment(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            comment_id = data.get('comment_id')
            
            comment = Comment.objects.get(id=comment_id)
            comment.delete()
            
            return JsonResponse({'message': 'Comment deleted'}, status=200)
        except Post.DoesNotExist:
            return JsonResponse({'message': 'Comment not found'}, status=404)
        except Exception as e:
            print(str(e))
            return JsonResponse({'message': str(e)}, status=500)

@csrf_exempt
def create_post(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_mood = Post.objects.create(
            author=request.user,
            body=data["body"]
        )

        new_mood.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
def create_comment(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_mood = Comment.objects.create(
            author=request.user,
            body=data["body"],
            parent_post=Post.objects.get(id=data['parent_post_id'])
        )

        new_mood.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

timeline/templates/posts/comment.html
{%  load static %}

<comment class="card p-4 !mb-4">
   <div class="flex justify-between items-center"> 
      <a class="flex items-center gap-1 mb-2" href="">
         <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png"> 
         <span class="font-bold hover:underline">{{ comment.author.profile.name }}</span>
         <span class="text-sm font-normal text-gray-400">@{{ comment.author.username }}</span>
      </a>
   </div>
   <p class="text-xl px-2">
       {{ comment.body }}
   </p>
   <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2">
      <a @click="repliesOpen = !repliesOpen" class="font-bold hover:underline cursor-pointer">
         {% if comment.replies.count or user.is_authenticated %}
         <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
            <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                  <path d="M24 22h-24l12-20z"/>
            </svg>
         </div>
         {% endif %}
            
         {% if comment.replies.count %}
         Replies
         <span id="repliescount-{{ comment.id }}" class="font-light text-gray-500 ml-1">{{ comment.replies.count }}</span>
            {% if user.is_authenticated %}
               Add Reply
            {% endif %}
         {% endif %}
      
      </a>
      <div class="flex items-center gap-4 [&>a:hover]:underline">
         {% include 'snip/likes_comment.html' %}   
         {% if user.is_authenticated and comment.author == user %}
         <a href="{% url 'timeline:comment-delete' comment.id %}">Delete</a>
         {% endif %}

      </div>

      <div x-show="repliesOpen" x-cloak class="basis-full mt-3 pl-8 grid grid-cols-1">

         {% for reply in comment.replies.all %}
         {% include 'posts/reply.html' %}
         {% endfor %}

         <form method="POST" action="{% url 'timeline:reply-sent' comment.id %}" class="replyform flex justify-between" autocomplete="off">
            {% csrf_token %}
            {{ replyform }}
            <!-- <input type="text" name="reply" placeholder="Add reply ..." maxlength="150"> -->
            <button class="block" type="submit">Submit</button>
         </form>
      </div>
   </div> 
</comment>

timeline/templates/posts/comment_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Delete Comment</h1>

{% include 'posts/comment.html' %}

<p class="my-6">Are you sure you want to delete this comment?</p>

<form method='POST'>
   {% csrf_token %}
   <button type="submit">Confirm</button>
   <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
</form>  

{% endblock %}

timeline/templates/posts/home.html
{% extends 'layouts/a.html' %}

{% block content %}
{% include 'includes/header.html' %}

{% for post in posts %}

{% include 'posts/post.html' %}


{% endfor %}
{% endblock %}

timeline/templates/posts/post.html
{% load static %}

<article class="card">
   <figure>
      <a href="{% url 'timeline:post' post.id %}">
         <!-- Cek apakah post.files memiliki file yang diunggah -->
         <!-- Jika post.files berisi file, tampilkan post.files.url -->
         <!-- Jika post.files kosong, tampilkan post.image sebagai fallback -->
         <img class="w-full" src="{% if post.files %}{{ post.files.url }}{% else %}{{ post.image }}{% endif %}" alt="Post Image">
      </a>
      <!-- <a href=""><img class="w-full" src="{{ post.image }}"></a> -->
   </figure>
   <div class="p-4 pb-2">
      <a class="flex items-center gap-1 mb-4" href="">
         <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
         <span class="font-bold hover:underline">{{ post.author.profile.realname }}</span>
         <span class="text-sm text-gray-400">@{{ post.author.username }}</span>
      </a>
      <p class="text-5xl mb-10 px-4 font1">{{ post.body }}</p>
      <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
         <!-- <a href="" class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white">Animals</a>
         <a href="" class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white">Black & White</a> -->
      </div>
      <div class="flex items-center justify-between text-sm px-2">
         <a class="font-bold hover:underline" href="{% url 'timeline:post' post.id %}">
            {% if post.comments.count %}
            Comments
            <span class="font-light text-gray-500 ml-1">{{ post.comments.count }}</span>
            {% else %}
            {% if user.is_authenticated %}
            Add comment
            {% endif %}
            {% endif %}
         </a>
         <div class="flex items-center gap-4 [&>a:hover]:underline">
            
            {% include 'snip/likes.html' %}   
      
            {% if user.is_authenticated and user == post.author %}
            <a href="{% url 'timeline:post-edit' post.id %}">Edit</a>
            <a href="{% url 'timeline:post-delete' post.id %}">Delete</a>
            {% endif %}

         </div>
      </div>
   </div>
</article>

timeline/templates/posts/post_create.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Create Post</h1>
<div class="card !p-8">
    
    <div class="flex items-center mb-6">
    </div>

    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="mt-1">Submit Post</button>
        <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a> cancel button 
    </form>
</div>

{% endblock %}

timeline/templates/posts/post_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<div class="md:flex items-center">
   <div class="w-full md:max-w-sm mr-6 md:[&>*>*>p]:text-4xl">
      {% include 'posts/post.html' %}
   </div>
   <div>
   <h1>Delete Post</h1>
   <p class="mb-6">Are you sure you want to delete this post?</p>
   
   <form method='POST'>
      {% csrf_token %}
      <button type="submit">Confirm</button>
      <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
   </form>
   </div>
</div>

{% endblock %}

timeline/templates/posts/post_edit.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Edit Post</h1>
<div class="card p-4">
    <div class="flex items-center mb-4">
        <img class="w-20 h-20 object-cover rounded-xl mr-4" src="{{ post.image }}">
        <!-- <h3 class="text-lg font-bold">{{ post.title }}</h3> -->
    </div>
    
    <div class="pb-2">
        <form method='POST'>
            {% csrf_token %}
            {{ form }}
            <div class="pt-4">

                <button type="submit">Submit</button>
                <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
            </div>
        </form>
    </div>
</div>


{% endblock %}

timeline/templates/posts/post_page.html
{% extends 'layouts/a.html' %}

{% block content %}

{% include 'posts/post.html' %}   

<div class="card !pb-0 -mt-4">
    <form method="POST" action="{% url 'timeline:comment-sent' post.id %}" class="flex items-center p-4" autocomplete="off">
        {% csrf_token %}
        {{ commentform }}
        <!-- <input type="text" name="comment" placeholder="Add comment ..." maxlength="150"> -->
        <button @click="open = false" class="block ml-2" type="submit">Submit</button>
    </form>
</div>

<div class="mb-20">

    <div id="tab-contents">
        {% for comment in post.comments.all %}
        {% include 'posts/comment.html' %}   
        {% endfor %}
    </div>
</div>

{% endblock %}

timeline/templates/posts/reply.html
{% load static %}

<reply class="flex items-end justify-between py-4 border-t">
   <div class="flex">
      <a href="">
         <img class="w-8 h-8 object-cover rounded-full mr-2" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
      </a>
      <div class="w-fit">
         {% if reply.author %}
         <a class="block" href="">
            <span class="font-bold hover:underline">{{ reply.author.profile.name }}</span>
            <span class="text-sm text-gray-400">@{{ reply.author.username }}</span>
         </a>
         {% else %}
         <span class="text-sm text-gray-500">no author</span>
         {% endif %}
         <div class="mr-3">{{ reply.body }}</div>
      </div>
   </div>
   <div class="flex items-center gap-4 [&>a:hover]:underline">
      {% include 'snip/likes_reply.html' %}   
      {% if user.is_authenticated and reply.author == user %}                    
      <a href="{% url 'timeline:reply-delete' reply.id %}">Delete</a>
      {% endif %}                    

   </div>
</reply>

timeline/templates/posts/reply_delete.html
{% extends 'layouts/a.html' %}

{% block content %}


<h1>Delete Reply</h1>

<div class=" card px-6 pt-3 text-md mb-6 [&>*>*>a]:text-sm">

   {% include 'posts/reply.html' %}   

</div>

<p class="mb-6">Are you sure you want to delete this reply?</p>

<form method='POST'>
   {% csrf_token %}
   <button type="submit">Confirm</button>
   <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
</form>


{% endblock %}